"""Expand prompts to 500+ — batch 2"""
import os
BASE = r"C:\ssClawy\aguidetocloud-revamp\content\prompts"
count = 0

def wp(cat, slug, title, desc, pt, plats, best, roles, diff, tags, tips):
    global count
    path = os.path.join(BASE, cat, f'{slug}.md')
    if os.path.exists(path): return
    ps = "\n".join(f"- {p}" for p in plats)
    rs = "\n".join(f"- {r}" for r in roles)
    ts = "\n".join(f"- {t}" for t in tags)
    tps = "\n".join(f"- {t}" for t in tips)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(f"""---
title: {title}
description: {desc}
prompt: >-
  {pt}
platforms:
{ps}
best_on: {best}
roles:
{rs}
use_case: {cat}
difficulty: {diff}
tags:
{ts}
---

## Tips for Best Results

{tps}
""")
    count += 1

data = [
# BRAINSTORMING +6
("brainstorming","swot-analysis","SWOT Analysis Generator","Create a structured SWOT analysis for any topic","Create a SWOT analysis for [TOPIC/PROJECT]. For each quadrant provide 4-5 specific points: (1) Strengths — internal advantages, (2) Weaknesses — internal gaps, (3) Opportunities — external factors to leverage, (4) Threats — external risks. End with 3 strategic recommendations.",["m365-copilot","chatgpt","claude"],"chatgpt",["manager","analyst","strategy"],"intermediate",["brainstorming","swot","analysis"],["Be specific and honest — vague SWOT analyses are useless","Include data or evidence for each point","Use the analysis to drive action not just awareness"]),
("brainstorming","problem-reframing","Problem Reframing Exercise","Reframe a problem from multiple perspectives","Help me reframe this problem: [DESCRIBE PROBLEM]. Look at it from: (1) The customer perspective, (2) The competitor perspective, (3) A completely different industry, (4) 10x scale — what if the problem was 10x bigger?, (5) Reverse — what if we caused this deliberately? For each reframe, suggest one solution.",["chatgpt","claude"],"claude",["manager","strategy"],"advanced",["brainstorming","reframing","creativity"],["The most creative solutions come from unusual perspectives","Try this with your team — different people see different reframes","Reframing breaks you out of tunnel vision"]),
("brainstorming","idea-prioritisation","Idea Prioritisation Matrix","Score and rank brainstormed ideas by impact and feasibility","Take these ideas: [LIST IDEAS]. Score each on: (1) Impact potential (1-10), (2) Feasibility (1-10), (3) Time to implement, (4) Risk level, (5) Strategic alignment. Calculate a priority score. Present as a ranked table with a recommendation for which 3 to pursue first.",["m365-copilot","chatgpt","claude"],"chatgpt",["manager","product-manager"],"intermediate",["brainstorming","prioritisation","decision"],["Score independently before discussing as a group","The highest-impact lowest-effort ideas are your quick wins","Parking an idea is not killing it — capture it for future review"]),
("brainstorming","reverse-brainstorm","Reverse Brainstorm","Find solutions by brainstorming how to make the problem worse","Help me reverse-brainstorm [PROBLEM]. List 10 ways to make this problem dramatically worse. Then for each, reverse engineer the opposite into a potential solution. Present as a table: Way to Make it Worse | Reversed Solution | Feasibility.",["chatgpt","claude"],"claude",["manager","team-lead"],"intermediate",["brainstorming","reverse","creative"],["This technique is especially good for teams that are stuck","The absurdity breaks creative blocks","Some of the best solutions come from the most ridiculous reverses"]),
("brainstorming","six-thinking-hats","Six Thinking Hats Analysis","Analyse a decision using de Bono Six Thinking Hats","Analyse [DECISION] using the Six Thinking Hats: (1) White Hat — facts and data, (2) Red Hat — emotions and gut feelings, (3) Black Hat — risks and cautions, (4) Yellow Hat — benefits and optimism, (5) Green Hat — creative alternatives, (6) Blue Hat — process and next steps. Synthesise into a recommendation.",["chatgpt","claude"],"claude",["manager","strategy"],"advanced",["brainstorming","six-hats","decision"],["Use with teams to ensure all perspectives are heard","The Red Hat gives permission to express feelings","End with the Blue Hat to define clear next steps"]),
("brainstorming","feature-wishlist","Feature Wishlist Prioritiser","Gather and prioritise feature ideas from stakeholders","Compile and prioritise this feature wishlist: [LIST FEATURES]. For each: (1) User story, (2) Which persona benefits, (3) Business value, (4) Technical complexity, (5) Dependencies. Group into Must Have, Should Have, Could Have, Will Not Have (MoSCoW).",["m365-copilot","chatgpt","claude"],"chatgpt",["product-manager","manager"],"intermediate",["brainstorming","features","prioritisation"],["Involve users in prioritisation not just internal teams","Must Haves should be fewer than 30 percent of total","Revisit priorities each planning cycle"]),

# IMAGE GENERATION +6
("image-generation","presentation-visual","Presentation Visual Generator","Create descriptions for AI-generated presentation visuals","Generate image prompts for a presentation about [TOPIC]. Create [NUMBER] image descriptions for: title slide, problem illustration, solution concept, data background, team image, and CTA visual. Specify: subject, composition, colour palette, style, and mood.",["dall-e","midjourney"],"dall-e",["creative","marketing"],"beginner",["image-generation","presentation","visual"],["Use consistent style across all presentation images","Corporate presentations need clean minimal images","Specify no text in generated images"]),
("image-generation","social-media-graphics","Social Media Image Series","Generate prompts for a cohesive social media image series","Create image generation prompts for a [NUMBER]-post social media series about [TOPIC]. Each image should: follow a consistent visual style, use brand colours [COLOURS], work at [DIMENSIONS], and leave space for text overlay.",["dall-e","midjourney"],"midjourney",["creative","marketing"],"intermediate",["image-generation","social-media","branding"],["Consistency across a series is more important than individual perfection","Test images at the size they will actually appear","Leave clear space for text"]),
("image-generation","icon-set","Custom Icon Set Designer","Generate prompts for a matching set of custom icons","Generate image prompts for [NUMBER] matching icons for [PURPOSE]. Theme: [THEME]. Each icon should: follow the same visual style, use a consistent colour palette, work at small sizes (64x64), and have a clean transparent background.",["dall-e","midjourney"],"dall-e",["creative","designer"],"intermediate",["image-generation","icons","design"],["Keep icons simple for small size recognition","Use consistent line weight","Test on both light and dark backgrounds"]),
("image-generation","blog-header","Blog Header Image Generator","Create eye-catching header images for blog posts","Create an image prompt for a blog header about [TOPIC]. The image should: be eye-catching, work at 1200x630, use [STYLE — photorealistic / illustration / abstract], avoid text, and complement [BRAND COLOURS].",["dall-e","midjourney"],"dall-e",["content-creator","marketing"],"beginner",["image-generation","blog","header"],["Blog headers should intrigue not explain","Dark images work better for white text overlay","Generate 3-4 variations and pick the best"]),
("image-generation","avatar-generator","Professional Avatar Creator","Generate prompts for professional AI avatars","Create an image prompt for a professional avatar in [STYLE] style. Specifications: head and shoulders, neutral background, warm expression, square format (1:1). Provide variations for LinkedIn, Teams, and Slack.",["dall-e","midjourney"],"dall-e",["all"],"beginner",["image-generation","avatar","profile"],["Keep professional avatars clean and recognisable","Use the same style across all platforms","Ensure it looks good at small chat thumbnail sizes"]),
("image-generation","concept-visualiser","Abstract Concept Visualiser","Create visual metaphors for abstract business concepts","Create an image prompt that visualises [ABSTRACT CONCEPT — digital transformation / collaboration / security / growth]. Use visual metaphor not literal representation. Style: [STYLE]. Mood: [MOOD]. Provide 3 different metaphor approaches.",["dall-e","midjourney"],"dall-e",["creative","marketing"],"advanced",["image-generation","concept","metaphor"],["Abstract concepts need visual metaphors","Test with colleagues — they should identify the concept","Simpler metaphors are more effective"]),

# PROJECT MANAGEMENT +5
("project-management","stakeholder-map","Stakeholder Map Creator","Map project stakeholders by influence and interest","Create a stakeholder map for [PROJECT]. For each stakeholder: name, interest level, influence level, current attitude, engagement strategy, communication frequency. Categorise into: Manage Closely, Keep Satisfied, Keep Informed, Monitor.",["m365-copilot","chatgpt","claude"],"chatgpt",["project-manager","manager"],"intermediate",["project-management","stakeholder","mapping"],["Update monthly as attitudes change","High influence + low support needs the most attention","Tailor communication to each stakeholder"]),
("project-management","lessons-learned","Lessons Learned Document","Capture project lessons learned in a structured format","Create a lessons learned document for [PROJECT]. Include: project overview, what went well (5-7 items), what could improve (5-7 items), what we would do differently, recommendations for future projects, key metrics vs plan. Tone: constructive.",["m365-copilot","chatgpt","claude"],"m365-copilot",["project-manager","team-lead"],"intermediate",["project-management","lessons-learned","retrospective"],["Conduct while the project is fresh","Include team and stakeholder perspectives","Share with other project managers"]),
("project-management","status-dashboard","Project Status Dashboard","Design a one-page project status reporting dashboard","Design a project status dashboard for [PROJECT]. Include: RAG status, timeline progress, budget tracker, risk summary, key metrics, recent accomplishments, upcoming milestones, decisions needed. One-page format.",["m365-copilot","chatgpt"],"m365-copilot",["project-manager","manager"],"intermediate",["project-management","dashboard","reporting"],["Update at the same time each week","Lead with decisions needed","Use traffic lights for instant visual status"]),
("project-management","scope-document","Project Scope Document","Define clear project scope with boundaries","Write a project scope document for [PROJECT]. Include: objectives, in-scope deliverables, out-of-scope items, assumptions, constraints, dependencies, acceptance criteria, change control process.",["m365-copilot","chatgpt","claude"],"m365-copilot",["project-manager","manager"],"intermediate",["project-management","scope","planning"],["Out-of-scope is as important as in-scope","Get stakeholder sign-off before starting","Reference scope when change requests arrive"]),
("project-management","resource-request","Resource Request Justification","Build a case for additional project resources","Write a resource request for [PROJECT] requesting [RESOURCE]. Include: current allocation, gap analysis, impact of not getting the resource, options, ROI, timeline needed. Present for [APPROVER].",["m365-copilot","chatgpt","claude"],"m365-copilot",["project-manager","manager"],"advanced",["project-management","resources","justification"],["Quantify the impact in days or revenue","Present options not just a single ask","Show you have optimised existing resources first"]),

# CUSTOMER SERVICE +7
("customer-service","empathy-response","Empathetic Customer Response","Write a response that acknowledges frustration and offers a solution","Write a response to this frustrated customer: [PASTE MESSAGE]. Structure: (1) Acknowledge frustration specifically, (2) Apologise sincerely, (3) Explain what happened briefly, (4) State what we will do to fix it, (5) Offer something extra, (6) Provide direct contact. Tone: empathetic, accountable.",["m365-copilot","chatgpt","claude"],"claude",["support","customer-success"],"intermediate",["customer-service","empathy","complaint"],["Mirror their language to show understanding","Never say I understand how you feel — show it through action","Follow up after resolution"]),
("customer-service","feature-request-response","Feature Request Response","Professionally respond to a feature request","Write a response to a customer requesting [FEATURE]. We [STATUS]. Include: (1) Thank them, (2) Acknowledge the value, (3) Be honest about status, (4) Offer alternatives, (5) Invite to feedback programme. Tone: appreciative, transparent.",["m365-copilot","chatgpt","claude"],"chatgpt",["support","product-manager"],"beginner",["customer-service","feature-request"],["Never promise a timeline you cannot keep","Collect requests systematically","Customers appreciate honesty over vague commitments"]),
("customer-service","refund-handler","Refund Request Handler","Process a refund request with appropriate tone","Handle this refund request: [SITUATION]. Policy: [POLICY]. Draft: (1) Acknowledge, (2) Review eligibility, (3) If approved: confirm amount and timeline, (4) If denied: explain compassionately with alternatives, (5) Offer support. Tone: fair, empathetic.",["m365-copilot","chatgpt","claude"],"chatgpt",["support"],"intermediate",["customer-service","refund","policy"],["Explain the policy before the decision","For borderline cases lean toward the customer","Always offer an alternative when denying"]),
("customer-service","welcome-onboarding","Customer Onboarding Welcome","Create a welcoming onboarding email sequence","Create an onboarding sequence for a new customer of [PRODUCT]. Email 1 (Day 0): Welcome and quick start. Email 2 (Day 3): Key feature. Email 3 (Day 7): Getting value. Email 4 (Day 14): Check-in. Each: warm, under 150 words, one clear action.",["m365-copilot","chatgpt","claude"],"chatgpt",["customer-success","support"],"beginner",["customer-service","onboarding","welcome"],["First 14 days determine long-term retention","Focus on one action per email","Include support contact in every email"]),
("customer-service","win-back","Customer Win-Back Email","Write a re-engagement email for lapsed customers","Write a win-back email for [CUSTOMER] who [LEFT/STOPPED] [TIMEFRAME] ago. Include: (1) Acknowledge absence without guilt, (2) Share improvements since they left, (3) Specific reason to return, (4) Limited-time incentive, (5) Easy one-click CTA. Tone: welcoming, not desperate.",["chatgpt","claude"],"chatgpt",["customer-success","marketing"],"intermediate",["customer-service","win-back","retention"],["Time emails 30, 60, and 90 days after lapse","Reference previous usage","Share genuine product improvements"]),
("customer-service","feedback-response","Public Review Response","Respond to a public review professionally","Write a response to this [TONE] public review: [PASTE]. Guidelines: (1) Thank them, (2) Address specific points, (3) For negative: acknowledge and explain actions, (4) For positive: reinforce, (5) Invite direct contact. Tone: professional, gracious. Under 100 words.",["chatgpt","claude"],"chatgpt",["support","marketing"],"beginner",["customer-service","review","reputation"],["Respond to every review within 24 hours","Never get defensive in public","Future customers read your responses more than the review"]),
("customer-service","service-recovery","Service Recovery Plan","Create a recovery plan after a major service failure","Create a recovery plan for [FAILURE] affecting [NUMBER] customers. Include: (1) Immediate actions (24 hours), (2) Communication sequence, (3) Root cause steps, (4) Compensation gesture, (5) Follow-up plan, (6) Prevention measures, (7) Recovery metrics.",["m365-copilot","chatgpt","claude"],"claude",["support","manager"],"advanced",["customer-service","recovery","incident"],["Speed matters more than perfection","Proactively reach out to customers","Track retention after the incident"]),

# RESEARCH +3
("research","literature-review","Literature Review Summary","Summarise research from multiple sources","Conduct a literature review on [TOPIC] using [NUMBER] sources. For each: citation, key findings, methodology, relevance. Synthesise: consensus, disagreements, gaps, implications for our work.",["chatgpt","claude","perplexity"],"perplexity",["analyst","researcher"],"advanced",["research","literature-review","synthesis"],["Cross-reference claims across sources","Note publication dates","Use Perplexity for source-backed research"]),
("research","market-research","Market Research Brief","Conduct quick market research on an industry","Research the market for [INDUSTRY/SEGMENT]. Cover: market size, key players, customer segments, trends (3-5), regulatory considerations, barriers to entry, opportunities. Cite sources and note confidence.",["chatgpt","perplexity"],"perplexity",["analyst","strategy"],"intermediate",["research","market","industry"],["Use multiple sources","Note estimated vs confirmed data","Update quarterly in fast-moving industries"]),
("research","best-practices","Best Practices Research","Find industry best practices for a specific area","Research best practices for [TOPIC] in [INDUSTRY]. Provide: (1) Top 5 practices with evidence, (2) Leading companies following each, (3) Common mistakes, (4) Implementation difficulty, (5) Where to start. Cite sources.",["chatgpt","perplexity"],"perplexity",["manager","consultant"],"intermediate",["research","best-practices","benchmarking"],["Best practices from one industry often transfer to another","Focus on practices with measurable outcomes","Start with easiest to implement"]),

# SUMMARISING +2
("summarising","book-summary","Book or Report Summary","Summarise a book or report into key takeaways","Summarise [TITLE] into: (1) One-sentence overview, (2) 5-7 key takeaways, (3) Main argument, (4) Most surprising finding, (5) How it applies to [MY CONTEXT], (6) Who should read this, (7) 3 quotes worth remembering. Under 500 words.",["chatgpt","claude"],"claude",["all"],"beginner",["summarising","book","takeaways"],["Include enough context to discuss the book without reading it","Highlight counterintuitive findings","Add one action item based on the content"]),
("summarising","thread-summary","Long Thread Summary","Summarise a long email or chat thread","Summarise this long thread into: (1) What started the conversation, (2) Key positions, (3) Where people agree, (4) Where they disagree, (5) Current status, (6) Open action items. Under 150 words. Write for someone joining now.",["m365-copilot","chatgpt","claude"],"m365-copilot",["all"],"beginner",["summarising","thread","chat"],["Focus on decisions and actions not full discussion","Note whose input is still needed","Great for catching up after being offline"]),

# MORE EMAIL
("email","cold-introduction","Warm Introduction Email","Write an introduction connecting two people","Write an introduction connecting [PERSON A] and [PERSON B]. Include: (1) Context on why they should connect, (2) One sentence about each person, (3) Suggestion for what to discuss, (4) Make it easy to reply. Tone: warm, brief.",["m365-copilot","chatgpt","claude"],"m365-copilot",["manager","sales"],"beginner",["email","introduction","networking"],["Ask both parties permission first","Make value clear for both sides","CC yourself for follow-up"]),
("email","bad-news-delivery","Delivering Bad News Professionally","Write an email that delivers bad news with empathy","Draft an email delivering: [BAD NEWS]. Include: (1) State the news directly first, (2) Explain the reason briefly, (3) Acknowledge impact, (4) Outline what we are doing, (5) Next steps, (6) Offer to discuss. Tone: empathetic, direct, accountable.",["m365-copilot","chatgpt","claude"],"claude",["manager","executive","hr"],"advanced",["email","bad-news","difficult"],["Never bury bad news — lead with it","Be direct but kind","Always include next steps"]),
("email","thank-you","Professional Thank You Email","Write a genuine thank you that strengthens the relationship","Write a thank you to [RECIPIENT] for [WHAT]. Make it: (1) Specific about impact, (2) Genuine, (3) Under 100 words, (4) Include forward-looking statement. Avoid generic phrases.",["m365-copilot","chatgpt","claude"],"m365-copilot",["all"],"beginner",["email","thank-you","appreciation"],["Mention the specific impact their help had","Send within 24 hours","CC their manager for extra recognition"]),

# MORE WRITING
("writing","executive-email","Executive Email Writer","Write a polished email for C-suite","Write an email to [EXECUTIVE] about [TOPIC]. Requirements: (1) Subject line that conveys the ask, (2) First sentence states bottom line, (3) Context in 2-3 sentences, (4) Clear ask, (5) Options if applicable, (6) Timeline. Under 150 words.",["m365-copilot","chatgpt","claude"],"claude",["manager","analyst"],"intermediate",["writing","executive","email"],["Put the ask in the first two sentences","If they can decide in 10 seconds your email is right","Include enough context to decide but no more"]),
("writing","tone-adjuster","Tone Adjuster","Rewrite content with a different tone","Rewrite this text with a [TARGET TONE — formal / casual / empathetic / urgent] tone: [PASTE TEXT]. Keep the exact same message but change the voice. Show before and after.",["m365-copilot","chatgpt","claude"],"claude",["all"],"beginner",["writing","tone","rewrite"],["The same message in the wrong tone causes problems","Match tone to audience","Compare versions to learn how tone shifts word choices"]),
("writing","bullet-to-narrative","Bullets to Narrative","Convert bullet points into flowing prose","Convert these bullet points into narrative text: [PASTE]. Requirements: (1) Smooth transitions, (2) Logical flow, (3) Maintain all information, (4) Add connecting context, (5) [TONE]. Target: [WORDS] words.",["m365-copilot","chatgpt","claude"],"chatgpt",["all"],"beginner",["writing","narrative","conversion"],["Great for turning meeting notes into reports","Narrative works better for executive summaries","Check accuracy — AI may infer unintended connections"]),
("writing","linkedin-article","LinkedIn Article Writer","Write a thought leadership article for LinkedIn","Write a LinkedIn article about [TOPIC] from my perspective as a [ROLE]. Structure: (1) Hook headline, (2) Opening story, (3) Main insight with 3 points, (4) Practical advice, (5) Closing question. Target: 800-1200 words. Tone: authoritative but conversational.",["chatgpt","claude"],"claude",["all"],"intermediate",["writing","linkedin","thought-leadership"],["Personal stories get 3x more engagement","Include one controversial point to drive discussion","End with a question for comments"]),

# MORE MEETINGS
("meetings","meeting-decision-tracker","Meeting Decision Tracker","Extract every decision from a meeting with rationale","Extract every decision from this meeting. For each: (1) Decision statement, (2) Who decided, (3) Rationale, (4) Impact, (5) Dissenting opinions, (6) Review date. Present as a numbered decision log.",["m365-copilot"],"m365-copilot",["project-manager","manager"],"intermediate",["meetings","decisions","tracking"],["A decision log prevents revisiting settled decisions","Include the rationale — most important part","Share immediately after the meeting"]),
("meetings","meeting-cost-calculator","Meeting Cost Estimator","Calculate the real cost of a meeting","Calculate meeting cost: [NUMBER] attendees, average salary [AMOUNT/YEAR], duration [MINUTES], frequency [FREQUENCY]. Show: cost per meeting, annual cost, opportunity cost. Is this meeting worth it? Suggest alternatives.",["chatgpt","claude"],"chatgpt",["manager","executive"],"beginner",["meetings","cost","efficiency"],["Making costs visible drives better meeting hygiene","Challenge any recurring meeting over 5000 per year","Replace status updates with async alternatives"]),
("meetings","facilitator-guide","Meeting Facilitation Guide","Get a facilitation plan for an important meeting","Create a facilitation plan for a [TYPE] meeting about [TOPIC]. Include: (1) Pre-meeting prep, (2) Ground rules, (3) Opening statement, (4) Discussion structure, (5) Managing dominant speakers, (6) Handling disagreement, (7) Decision method, (8) Closing and actions.",["chatgpt","claude"],"claude",["manager","team-lead","hr"],"advanced",["meetings","facilitation","management"],["Send ground rules before the meeting","Use a parking lot for off-topic points","Summarise decisions verbally before ending"]),

# MORE PRESENTATIONS
("presentations","workshop-slides","Workshop Slide Deck","Create interactive workshop slides","Create a [NUMBER]-slide workshop deck for [TOPIC]. Include: welcome/objectives, 3-4 content sections, interactive exercises between sections, discussion questions, summary/takeaways, resources. Add facilitator notes.",["m365-copilot","chatgpt","claude"],"m365-copilot",["trainer","manager"],"intermediate",["presentations","workshop","interactive"],["Include timing notes on every slide","Mix individual and group activities","Build in breaks every 45-60 minutes"]),
("presentations","quarterly-review","Quarterly Review Slides","Create a structured QBR presentation","Create a [NUMBER]-slide QBR deck for [DEPARTMENT]. Include: overview and metrics, highlights, challenges, financial performance, customer insights, learnings, next priorities, support needed. Headline insight on each slide.",["m365-copilot"],"m365-copilot",["manager","executive"],"intermediate",["presentations","qbr","review"],["Lead with the headline finding","Use chart titles that state the insight","End with specific asks"]),

# MORE DATA-ANALYSIS
("data-analysis","survey-analyser","Survey Results Analyser","Analyse survey responses and extract insights","Analyse these survey results. Provide: (1) Response rate and validity, (2) Key quantitative findings, (3) Open-ended theme analysis, (4) Segments that differ significantly, (5) Top 3 actionable insights, (6) Follow-up recommendations.",["m365-copilot","chatgpt","claude"],"m365-copilot",["analyst","hr","manager"],"intermediate",["data-analysis","survey","insights"],["Look for patterns not just averages","Open-ended responses contain the most value","Compare across segments"]),
("data-analysis","correlation-finder","Correlation Finder","Identify relationships between variables","Analyse for correlations between [VARIABLES]. For each significant one: (1) State the relationship, (2) Strength, (3) Direction, (4) Possible explanations, (5) Caveats. Create a correlation matrix.",["m365-copilot","chatgpt"],"m365-copilot",["analyst","researcher"],"advanced",["data-analysis","correlation","statistics"],["Correlation does not imply causation","Look for confounding variables","Visualise correlations to spot patterns"]),

# MORE COPILOT COWORK
("copilot-cowork","quarterly-cleanup","Quarterly Digital Cleanup","Have Cowork clean up your files and subscriptions","Perform a quarterly cleanup: (1) Find unfinished files for review, (2) Identify unread email subscriptions, (3) Flag inactive Teams channels, (4) Check expired sharing permissions, (5) Summarise unused licences. Present a cleanup checklist.",["m365-copilot"],"m365-copilot",["all"],"beginner",["cowork","cleanup","productivity"],["Run quarterly to prevent clutter","Review before taking action","Good digital hygiene improves security"]),
("copilot-cowork","research-and-brief","Deep Research and Executive Brief","Have Cowork research and produce deliverables","Research [TOPIC] and produce: (1) Detailed research document in Word with sources, (2) One-page executive brief, (3) 3-slide PowerPoint summary, (4) Draft email to [RECIPIENTS] with brief attached. Check in after research before final outputs.",["m365-copilot"],"m365-copilot",["analyst","manager"],"advanced",["cowork","research","multi-app"],["Review research before final outputs","Specify audience for each deliverable","This saves the most time on multi-deliverable tasks"]),

# MORE CLAUDE COWORK
("claude-cowork","design-sprint","Remote Design Sprint Facilitator","Run a compressed design sprint with your team","Facilitate a 2-hour design sprint for [CHALLENGE]. Structure: (1) Problem definition (10 min), (2) How Might We questions (15 min), (3) Rapid ideation — 8 ideas in 8 minutes, (4) Dot voting, (5) Solution sketching (20 min), (6) Critique, (7) Next steps. Keep energy high.",["claude"],"claude",["product-manager","designer"],"advanced",["claude-cowork","design-sprint","innovation"],["Time pressure forces decisive thinking","Independent ideation first to avoid groupthink","Goal is direction not finished design"]),
("claude-cowork","team-charter","Team Charter Builder","Collaboratively build a team charter","Help us build a team charter. Each person contributes to: (1) Mission, (2) Values (2 each), (3) Working agreements, (4) Decision-making process, (5) Conflict resolution, (6) Success measures. Claude: synthesise, identify conflicts, propose unified charter.",["claude"],"claude",["manager","team-lead"],"intermediate",["claude-cowork","charter","culture"],["Only works if team creates it together","Review quarterly","Reference during conflicts"]),

# ADDITIONAL FILL — more per category
("troubleshooting","teams-audio-fix","Teams Audio Troubleshooting","Self-service guide for Teams audio issues","Create a troubleshooting guide for Teams audio: (1) Cannot hear others, (2) Others cannot hear me, (3) Echo, (4) Audio cutting out, (5) Wrong device. For each: ordered fix steps, settings locations, when to contact IT. Write for non-technical users.",["m365-copilot","chatgpt"],"chatgpt",["it-admin","support"],"beginner",["troubleshooting","teams","audio"],["Teams audio is the top IT support ticket","Include the Teams test call as step one","Add a quick reference card"]),
("onboarding","welcome-email","New Hire Welcome Email","Write a warm welcome email for a new team member","Write a welcome email for [NAME] joining as [ROLE] on [DATE]. Include: (1) Warm welcome from [MANAGER], (2) Day 1 expectations, (3) First week overview, (4) Key contacts, (5) Essential links, (6) Something fun about the team. Tone: excited, supportive.",["m365-copilot","chatgpt","claude"],"m365-copilot",["manager","hr"],"beginner",["onboarding","welcome","new-hire"],["Send the day before they start","Include practical details","A personal touch makes the difference"]),
("onboarding","buddy-guide","Onboarding Buddy Guide","Create a guide for someone mentoring a new hire","Create a buddy guide for helping [ROLE] settle in. Include: (1) Buddy expectations, (2) Week-by-week checklist, (3) Common questions and answers, (4) Cultural norms, (5) Signs they might be struggling, (6) Handoff when buddying ends.",["m365-copilot","chatgpt","claude"],"chatgpt",["hr","manager"],"beginner",["onboarding","buddy","mentor"],["Buddies should be peers not managers","Schedule regular check-ins","Share real culture not just the handbook"]),
("onboarding","tool-rollout","New Tool Rollout Plan","Create a rollout plan for a new tool","Create a rollout plan for [TOOL] for [NUMBER] users over [TIMEFRAME]. Include: (1) Pre-launch emails, (2) Training options, (3) Pilot group and feedback, (4) Full rollout phases, (5) Support plan and FAQ, (6) Success metrics, (7) Post-rollout survey.",["m365-copilot","chatgpt","claude"],"m365-copilot",["it-admin","manager"],"intermediate",["onboarding","rollout","adoption"],["Start with champions for the pilot","Multiple training formats","Measure adoption at 30, 60, 90 days"]),
("onboarding","change-readiness","Change Readiness Assessment","Evaluate readiness for a change","Create a change readiness assessment for [CHANGE]. Include: (1) 10 ADKAR-based questions, (2) Rating scale, (3) Scoring guide, (4) Risk areas, (5) Recommended actions. Format as a distributable survey.",["m365-copilot","chatgpt","claude"],"chatgpt",["manager","hr"],"intermediate",["onboarding","change","readiness"],["Assess BEFORE announcing the change","Low scores show where to invest","Reassess at each rollout phase"]),
("onboarding","champion-network","Champion Network Setup","Create a change champion programme","Design a champion programme for [CHANGE]. Include: (1) Role description, (2) Selection criteria, (3) Training plan, (4) Communication toolkit, (5) Recognition programme, (6) Reporting cadence. Target: [NUMBER] champions across [DEPARTMENTS].",["m365-copilot","chatgpt","claude"],"m365-copilot",["manager","hr","it-admin"],"intermediate",["onboarding","champions","adoption"],["Choose respected peers not just enthusiastic ones","Give champions early access","Recognise publicly to attract more"]),

# LEGAL
("legal","contract-review","Contract Review Checklist","Review a contract and flag key terms","Review this contract: (1) Key terms summary, (2) Obligations per party, (3) Termination conditions, (4) Liability clauses, (5) Payment terms, (6) Auto-renewal provisions, (7) Red flags, (8) Missing clauses. Note: for initial review only — legal must approve.",["m365-copilot","chatgpt","claude"],"claude",["legal","manager","procurement"],"advanced",["legal","contract","review"],["AI review is for screening — lawyer must approve","Flag auto-renewal clauses","Check governing law jurisdiction"]),
("legal","compliance-checklist","Compliance Checklist Generator","Create a compliance checklist for a regulation","Create a checklist for [REGULATION]. Include: requirement, evidence needed, status, owner, remediation steps, review frequency. Focus on [ORG TYPE]. Pre-populate status as Not Assessed.",["m365-copilot","chatgpt","claude"],"m365-copilot",["compliance","it-admin"],"intermediate",["legal","compliance","checklist"],["Start with a gap assessment","Focus on high-risk areas first","Maintain evidence continuously"]),
("legal","privacy-notice","Privacy Notice Drafter","Draft a privacy notice for a product or service","Draft a privacy notice for [PRODUCT]. Cover: data collected, usage, legal basis, third parties, retention, user rights, cookies, contact details. Comply with [REGULATION]. Use plain language.",["chatgpt","claude"],"claude",["legal","compliance"],"advanced",["legal","privacy","gdpr"],["Plain language reduces trust issues","Be specific about retention periods","Have legal review before publishing"]),
("legal","vendor-risk","Vendor Risk Assessment","Evaluate the risk of a third-party vendor","Assess [VENDOR] providing [SERVICE]. Evaluate: data access, security certs, DPA status, sub-processors, incident notification, insurance, data residency, exit strategy. Rate overall risk.",["m365-copilot","chatgpt","claude"],"m365-copilot",["legal","procurement","it-admin"],"advanced",["legal","vendor","risk"],["Assess before signing contracts","Higher risk = more frequent reviews","Include in overall risk register"]),

# FINANCE extras
("finance","roi-analysis","ROI Analysis Builder","Calculate ROI for a proposed initiative","Calculate ROI for [INITIATIVE]. Include: total investment, quantified benefits, payback period, 3-year NPV, IRR, break-even, sensitivity analysis, risk-adjusted ROI. Present with recommendation.",["m365-copilot","chatgpt"],"m365-copilot",["finance","manager"],"advanced",["finance","roi","investment"],["Be conservative with benefit estimates","Include non-financial benefits separately","State discount rate assumptions"]),
("finance","forecast-model","Revenue Forecast Model","Build a forecast from historical data","Using [PERIOD] of data, forecast [METRIC] for [PERIOD]. Include: trend analysis, seasonal adjustments, best/expected/worst scenarios, key assumptions, confidence level. Present with trend chart.",["m365-copilot"],"m365-copilot",["finance","analyst"],"advanced",["finance","forecast","modelling"],["State assumptions clearly","Include 3 scenarios","Update monthly with new actuals"]),

# SALES extras
("sales","discovery-questions","Discovery Call Questions","Prepare structured discovery questions for a sales call","Create discovery questions for a call with [PROSPECT TYPE] evaluating [SOLUTION]. Include: (1) Rapport opener, (2) Current state questions, (3) Impact questions, (4) Vision questions, (5) Process questions, (6) Next steps. Order broad to specific.",["chatgpt","claude"],"chatgpt",["sales","account-manager"],"intermediate",["sales","discovery","questions"],["70 percent listening, 30 percent talking","Note exact phrases they use — mirror in proposals","Take detailed notes"]),
("sales","quarterly-business-review-sales","QBR for Existing Customer","Structure a QBR presentation for retention and expansion","Create a QBR outline for [CUSTOMER]. Include: relationship summary, usage metrics, ROI achieved, support summary, roadmap highlights, expansion opportunities, action items. Slide outline with talking points.",["m365-copilot","chatgpt","claude"],"m365-copilot",["sales","customer-success"],"advanced",["sales","qbr","customer-success"],["Lead with their success not your features","Include specific ROI numbers","End with expansion discussion"]),

# MARKETING extras
("marketing","case-study-outline","Customer Success Story","Structure a compelling case study","Create a case study outline for [CUSTOMER] who achieved [RESULT] using [PRODUCT]. Include: headline with result, customer profile, problem, why they chose us, implementation, results with metrics, customer quote. Include interview questions.",["chatgpt","claude"],"claude",["marketing","customer-success"],"intermediate",["marketing","case-study","content"],["Lead with the result in the headline","Include specific numbers","Get the customer quote on record"]),

# CREATIVE extras
("creative","naming-brainstorm","Naming Brainstorm","Generate name ideas for a product or project","Generate [NUMBER] name ideas for [WHAT]. Requirements: easy to pronounce, available as domain, no negative meanings, fits [BRAND] personality. Style: [STYLE]. For top 5, explain why each works.",["chatgpt","claude"],"chatgpt",["creative","product-manager"],"beginner",["creative","naming","branding"],["Test names with people outside the project","Check trademark databases","Say each name 10 times — does it still sound good"]),

# PRODUCTIVITY extras
("productivity","annual-goals","Annual Goal Setting","Set structured personal or team goals","Help me set goals for [YEAR]. Role: [ROLE]. Priorities: [LIST]. Create: (1) 3-5 SMART goals, (2) Quarterly milestones, (3) Supporting habits, (4) Obstacles and mitigation, (5) Tracking plan. Balance development with deliverables.",["chatgpt","claude"],"chatgpt",["all"],"intermediate",["productivity","goals","planning"],["Fewer focused goals beat many scattered ones","Include a growth goal","Review quarterly and adjust"]),
("productivity","weekly-plan","Weekly Planning Session","Create a focused plan for the week","My priorities: [LIST]. Meetings: [KEY MEETINGS]. Deadlines: [DEADLINES]. Create: (1) Top 3 outcomes for Friday, (2) Daily focus blocks, (3) Meetings to prepare for, (4) Tasks to delegate, (5) One thing to learn. Keep realistic at 6 productive hours per day.",["m365-copilot","chatgpt","claude"],"m365-copilot",["all"],"beginner",["productivity","weekly","planning"],["Plan Monday morning for a fresh start","Identify one must-win task","Leave Friday for catch-up"]),

# COMMUNICATION extras
("communication","crisis-faq","Crisis FAQ Generator","Create an FAQ for an emerging crisis","Create an urgent FAQ for [CRISIS] targeting [AUDIENCE]. Include: (1) What happened, (2) 15-20 anticipated questions by frequency, (3) Approved answers, (4) Default response for unlisted questions, (5) Spokesperson contacts. Update as new info becomes available.",["m365-copilot","chatgpt","claude"],"claude",["communications","manager"],"advanced",["communication","crisis","faq"],["Distribute to all customer-facing staff immediately","Update every 4 hours during active crisis","Include version number and timestamp"]),
("communication","stakeholder-update","Stakeholder Progress Update","Write a concise project update for stakeholders","Write an update for [PROJECT] for [PERIOD]. Structure: (1) Status (RAG), (2) Accomplishments, (3) Upcoming milestones, (4) Risks and mitigation, (5) Decisions needed, (6) Budget status. One page. Traffic light indicators.",["m365-copilot","chatgpt","claude"],"m365-copilot",["project-manager","manager"],"intermediate",["communication","stakeholder","reporting"],["Lead with decisions needed","Be honest about risks","Consistent cadence weekly or fortnightly"]),

# CYBERSECURITY extras
("cybersecurity","tabletop-exercise","Tabletop Exercise Designer","Create a cybersecurity tabletop exercise","Design a tabletop exercise for [SCENARIO]. Include: narrative with escalating phases, inject cards, discussion questions, roles to test, evaluation criteria, facilitation guide, post-exercise report template. Duration: [HOURS].",["chatgpt","claude"],"claude",["cybersecurity","it-admin"],"advanced",["cybersecurity","tabletop","incident-response"],["Run at least annually","Include non-IT stakeholders","Should challenge but not stall"]),

# ADDITIONAL CROSS-PLATFORM to fill remaining
("summarising","competitive-intel-summary","Competitive Intelligence Summary","Summarise competitive intelligence from multiple sources","Summarise competitive intel from [SOURCES]. For each competitor: strengths, vulnerabilities, recent moves, customer sentiment vs us, recommended response. One-page competitive summary.",["m365-copilot","chatgpt","perplexity"],"m365-copilot",["sales","product-manager"],"advanced",["summarising","competitive","intelligence"],["Combine internal and public information","Update monthly","Be honest about where competitors are better"]),
("planning","capacity-planning","Team Capacity Planning","Calculate team capacity and plan workload","Plan capacity for [TEAM] for [PERIOD]. Members: [NUMBER] with [ROLES]. Map committed projects against capacity. Identify: over-allocation, under-allocation, hiring needs. Capacity chart.",["m365-copilot","chatgpt"],"m365-copilot",["manager","project-manager"],"intermediate",["planning","capacity","resource"],["Account for meetings and context switching","Build in 20 percent buffer","Review monthly"]),
("planning","okr-generator","OKR Generator","Create measurable OKRs","Generate OKRs for [TEAM] for [PERIOD]. Create [NUMBER] objectives with 3-4 key results each. Objectives: ambitious and qualitative. Key results: specific, measurable, with targets. Align with: [COMPANY GOAL]. Include confidence ratings.",["m365-copilot","chatgpt","claude"],"chatgpt",["manager","executive"],"intermediate",["planning","okr","goals"],["Key results must be measurable","Set confidence at 70 percent for stretch","Score at end of each period"]),
]

for args in data:
    wp(*args)

from pathlib import Path
total = sum(1 for p in Path(BASE).rglob('*.md') if p.name != '_index.md')
print(f'Created {count} prompts')
print(f'GRAND TOTAL: {total}')
