"""Final push to 500 — add 4 unique prompts to every category under 12"""
import os
from pathlib import Path

BASE = r"C:\ssClawy\aguidetocloud-revamp\content\prompts"
count = 0

def wp(cat, slug, title, desc, pt, plats, best, roles, diff, tags, tips):
    global count
    path = os.path.join(BASE, cat, f"{slug}.md")
    if os.path.exists(path): return
    ps = "\n".join(f"- {p}" for p in plats)
    rs = "\n".join(f"- {r}" for r in roles)
    ts = "\n".join(f"- {t}" for t in tags)
    tps = "\n".join(f"- {t}" for t in tips)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"""---
title: {title}
description: {desc}
prompt: >-
  {pt}
platforms:
{ps}
best_on: {best}
roles:
{rs}
use_case: {cat}
difficulty: {diff}
tags:
{ts}
---

## Tips for Best Results

{tps}
""")
    count += 1

P = [
# ANALYST-AGENT +4
("analyst-agent","cohort-analysis","Cohort Analysis","Analyse user or customer behaviour by cohort","Group users from this data into cohorts by [CRITERIA — sign-up month / first purchase / plan tier]. Track [METRIC — retention / revenue / engagement] over [PERIODS]. Show: cohort table, trend chart, strongest vs weakest cohort, and 3 actionable insights.",["m365-copilot"],"m365-copilot",["analyst","product-manager"],"advanced",["analyst","cohort","retention"],["Cohort analysis reveals patterns averages hide","At least 6 months of data for meaningful trends","Compare cohorts to identify what changed"]),
("analyst-agent","ab-test-results","A/B Test Results Analyser","Analyse A/B test results for statistical significance","Analyse this A/B test: Control [A METRICS] vs Variant [B METRICS]. Determine: (1) Statistical significance (p-value), (2) Confidence interval, (3) Effect size, (4) Sample size adequacy, (5) Winner recommendation with caveats, (6) Whether to continue testing.",["m365-copilot"],"m365-copilot",["analyst","marketing","product-manager"],"advanced",["analyst","ab-test","statistics"],["Do not call a winner too early","Check for novelty effect","Segment results by user type"]),
("analyst-agent","data-storytelling","Data Storytelling Narrative","Turn analysis results into a compelling narrative","Take these analysis results: [DESCRIBE FINDINGS]. Turn them into a data story for [AUDIENCE]. Include: (1) The headline insight (one sentence), (2) Why it matters (so what), (3) The evidence (charts and numbers), (4) What caused it, (5) What to do about it. Write for people who do not love data.",["m365-copilot"],"m365-copilot",["analyst","manager"],"intermediate",["analyst","storytelling","narrative"],["Start with the so what not the methodology","One insight per page or slide","Use charts that support the narrative"]),
("analyst-agent","benchmark-comparison","Benchmark Comparison","Compare your metrics against industry benchmarks","Compare our metrics against industry benchmarks. Our data: [PASTE KEY METRICS]. Industry: [INDUSTRY]. For each metric: (1) Our value, (2) Industry benchmark, (3) Percentile ranking, (4) Gap analysis, (5) Whether the gap matters and what to do about it. Flag where we significantly lag or lead.",["m365-copilot"],"m365-copilot",["analyst","manager","executive"],"intermediate",["analyst","benchmark","comparison"],["Use reputable benchmark sources","Context matters — not all benchmarks apply","Focus on gaps that impact business outcomes"]),

# RESEARCHER-AGENT +4
("researcher-agent","policy-impact-analysis","Policy Impact Analysis","Research how a new policy or regulation will affect your organisation","Research [NEW POLICY/REGULATION] and assess impact on [ORGANISATION TYPE]. Cover: (1) What the policy requires, (2) Effective date and enforcement timeline, (3) Who is affected, (4) Compliance requirements, (5) Cost and effort to comply, (6) Penalties for non-compliance, (7) How peers are responding. Cite official sources.",["m365-copilot"],"m365-copilot",["compliance","manager","legal"],"advanced",["researcher","policy","regulation","impact"],["Focus on what is confirmed not speculated","Include implementation timeline","Consult legal for final interpretation"]),
("researcher-agent","trend-report","Emerging Trends Report","Research emerging trends in a specific domain","Research emerging trends in [DOMAIN] for [YEAR]. Identify: (1) Top 5 trends with evidence, (2) Which are hype vs real adoption, (3) Key players driving each trend, (4) Timeline to mainstream, (5) Implications for [OUR CONTEXT], (6) Recommended actions. Distinguish predictions from confirmed developments.",["m365-copilot"],"m365-copilot",["strategy","manager","analyst"],"intermediate",["researcher","trends","emerging","analysis"],["Distinguish hype from real adoption","Include contrarian viewpoints","Set a calendar reminder to revisit in 6 months"]),
("researcher-agent","roi-evidence","ROI Evidence Finder","Find external evidence to support an ROI business case","Find external evidence supporting the ROI of [INITIATIVE — Copilot / cloud migration / automation / AI adoption]. Look for: (1) Published case studies with specific numbers, (2) Analyst reports (Forrester TEI, Gartner), (3) Customer testimonials, (4) Industry benchmarks, (5) Academic research. Compile as a sourced evidence appendix for a business case.",["m365-copilot"],"m365-copilot",["analyst","manager","sales"],"intermediate",["researcher","roi","evidence","business-case"],["Prioritise case studies from similar industries","Note sample sizes and methodology quality","Include both optimistic and conservative estimates"]),
("researcher-agent","competitor-watch","Competitor Watch Brief","Monitor competitor announcements and movements","Create a competitor watch brief for [COMPETITOR] covering the last [PERIOD]. Track: (1) Product announcements, (2) Pricing changes, (3) New partnerships, (4) Executive hires, (5) Customer wins or losses, (6) Analyst commentary, (7) What this means for us. Cite every finding.",["m365-copilot"],"m365-copilot",["sales","product-manager","strategy"],"intermediate",["researcher","competitor","monitoring"],["Set up regular monitoring cadence","Combine public sources with field intelligence","Focus on implications not just facts"]),

# ONENOTE +4
("onenote","client-meeting-notes","Client Meeting Notes Template","Set up a structured template for client meeting notes","Set up a client meeting notes template in OneNote. Sections: (1) Client details and attendees, (2) Agenda items, (3) Discussion notes by agenda item, (4) Commitments we made, (5) Commitments they made, (6) Follow-up actions with owners and dates, (7) Next meeting date. Include a satisfaction indicator.",["m365-copilot"],"m365-copilot",["sales","consultant","manager"],"beginner",["onenote","client","meeting","template"],["Use the same template for every client meeting for consistency","Review commitments at the start of the next meeting","Share notes with the client within 24 hours"]),
("onenote","learning-journal","Learning Journal","Create a structured learning journal for professional development","Set up a learning journal in OneNote. Structure: (1) Weekly learning entries (date, what I learned, source, how I will apply it), (2) Book and article notes section, (3) Course notes with key takeaways, (4) Skills tracking (skill, level, target, progress), (5) Questions to explore, (6) Monthly reflection on growth.",["m365-copilot"],"m365-copilot",["all"],"beginner",["onenote","learning","journal","development"],["Write entries immediately after learning — memory fades fast","Review monthly to see patterns in what you are learning","Connect learning to action — how will you use this"]),
("onenote","project-decision-log","Project Decision Log","Maintain a running log of all project decisions","Set up a decision log in OneNote for [PROJECT]. For each decision: date, decision statement, context (why now), options considered, chosen option, rationale, who decided, review date. Include a search-friendly index at the top.",["m365-copilot"],"m365-copilot",["project-manager","manager"],"intermediate",["onenote","decisions","log","governance"],["Prevents the 'why did we decide that' question","Include rationale — the most important part","Review decisions quarterly for relevance"]),
("onenote","research-notebook","Research Collection Notebook","Organise research from multiple sources into a structured notebook","Set up a research notebook in OneNote for [TOPIC]. Sections: (1) Research questions to answer, (2) Source notes (one page per source with citation, key points, credibility rating), (3) Synthesis page (themes across sources), (4) Gaps and questions, (5) Conclusions and recommendations.",["m365-copilot"],"m365-copilot",["analyst","researcher","manager"],"intermediate",["onenote","research","notebook","organisation"],["One page per source keeps things searchable","Rate source credibility to weight findings","Synthesis is where the real insight happens"]),

# LOOP +4
("loop","project-retrospective","Project Retrospective Board","Run a collaborative project retrospective in Loop","Create a retrospective board for [PROJECT]. Sections: (1) What went well — team adds items live, (2) What to improve, (3) What puzzled us, (4) Vote on top items (each person picks 3), (5) Action items from top-voted (owner, deadline, success measure). Claude or Copilot: group themes as items come in.",["m365-copilot"],"m365-copilot",["project-manager","team-lead"],"intermediate",["loop","retrospective","team","improvement"],["Everyone types simultaneously for honest input","Group themes to prevent repetitive discussion","Track actions from previous retros"]),
("loop","weekly-standup-board","Weekly Standup Board","Create a persistent weekly standup board the team updates","Create a weekly standup board. Columns per team member: What I did this week, What I am doing next week, Blockers. Include: team health check (1-5 mood rating), wins to celebrate section, and a help-needed board. Refresh weekly but keep history.",["m365-copilot"],"m365-copilot",["team-lead","manager"],"beginner",["loop","standup","weekly","team"],["Replace status meetings with this async board","Everyone updates by Friday noon","Review blockers as a team"]),
("loop","stakeholder-communication","Stakeholder Communication Hub","Create a shared hub for all stakeholder communications","Create a stakeholder communication hub in Loop for [PROJECT]. Include: (1) Stakeholder register (name, role, interest, influence), (2) Communication log (date, channel, message, response), (3) Upcoming communications calendar, (4) Approved messaging and talking points, (5) Feedback tracker.",["m365-copilot"],"m365-copilot",["project-manager","communications"],"intermediate",["loop","stakeholder","communication","hub"],["Single source of truth prevents mixed messages","Log every stakeholder interaction","Keep talking points updated"]),
("loop","team-knowledge-wiki","Team Knowledge Wiki","Build a living team wiki that everyone maintains","Create a team wiki in Loop for [TEAM]. Sections: (1) Team mission and goals, (2) Who does what (roles and responsibilities), (3) How we work (processes, tools, ceremonies), (4) Key resources and links, (5) FAQ for new joiners, (6) Glossary of team-specific terms. Everyone on the team can edit and keep current.",["m365-copilot"],"m365-copilot",["team-lead","manager"],"beginner",["loop","wiki","knowledge","team"],["Assign section owners for maintenance","Review quarterly as a team","Great for onboarding new members"]),

# CUSTOMER-SUPPORT +4
("customer-support","ticket-analysis","Support Ticket Trend Analysis","Analyse support ticket patterns to prevent recurring issues","Analyse support tickets from [PERIOD]. Identify: (1) Top 10 issue categories by volume, (2) Trending up vs down vs stable, (3) Average resolution time by category, (4) Tickets that could be prevented with documentation, (5) Tickets that need a product fix, (6) Staffing implications. Recommend 3 actions to reduce ticket volume.",["m365-copilot","chatgpt"],"m365-copilot",["support","manager","analyst"],"intermediate",["support","analysis","tickets","trends"],["Categorise tickets consistently for meaningful analysis","Top issue = top opportunity for self-service content","Share findings with product team for permanent fixes"]),
("customer-support","sla-report","SLA Performance Report","Create a service level agreement performance report","Create an SLA performance report for [PERIOD]. Include: (1) SLA targets vs actual for each metric, (2) Breach count and root causes, (3) Trend vs previous periods, (4) At-risk SLAs for next period, (5) Improvement actions, (6) Customer satisfaction correlation with SLA performance.",["m365-copilot","chatgpt"],"m365-copilot",["support","manager","operations"],"intermediate",["support","sla","performance","reporting"],["Report on SLAs proactively not just when breached","Correlate SLA performance with CSAT","Identify systemic causes of breaches"]),
("customer-support","response-templates","Tone-Matched Response Templates","Create support response templates for different customer emotions","Create response templates for these customer emotional states: (1) Angry and frustrated, (2) Confused and lost, (3) Anxious and worried, (4) Happy but has a question, (5) Disappointed after a promise broken. Each template: acknowledge emotion, match energy appropriately, provide solution, next step. Include tone guidance.",["m365-copilot","chatgpt","claude"],"claude",["support"],"intermediate",["support","templates","tone","empathy"],["Match the customer's emotional energy level","Angry customers need acknowledgement before solutions","Happy customers are your best advocates — nurture them"]),
("customer-support","onboarding-check-in","Customer Onboarding Check-In","Draft a proactive check-in email during customer onboarding","Draft a proactive check-in email for [CUSTOMER] who is [DAYS] days into onboarding with [PRODUCT]. Include: (1) Warm personal check-in, (2) Ask how their experience has been, (3) Share a tip they probably have not discovered, (4) Offer a quick call if they need help, (5) Link to helpful resource. Tone: caring, not salesy. Under 100 words.",["m365-copilot","chatgpt","claude"],"chatgpt",["customer-success","support"],"beginner",["support","onboarding","check-in","proactive"],["Proactive outreach prevents churn","Share genuinely helpful tips not marketing","Time check-ins at day 3, 7, 14, and 30"]),

# TRAINING +4
("training","role-play-scenarios","Training Role-Play Scenarios","Create realistic role-play scenarios for skills practice","Create [NUMBER] role-play scenarios for practicing [SKILL]. Each: (1) Situation setup, (2) Character briefs for participants, (3) Hidden objectives, (4) Evaluation criteria, (5) Debrief questions. Increase difficulty progressively.",["chatgpt","claude"],"claude",["trainer","manager","hr"],"advanced",["training","role-play","practice"],["Give character briefs privately for realism","Debrief immediately after each scenario","Record for later review if consented"]),
("training","certification-study-plan","Certification Study Plan","Create a structured study plan for a professional certification","Create a study plan for [CERTIFICATION — AZ-900 / PMP / CISSP / AWS]. Include: (1) Exam overview and passing score, (2) Weekly study schedule for [WEEKS] weeks, (3) Topics by priority and weight, (4) Resources (official study guide, practice tests, videos), (5) Practice test strategy, (6) Exam day tips. Based on [AVAILABLE HOURS] study hours per week.",["chatgpt","claude","perplexity"],"perplexity",["all"],"intermediate",["training","certification","study-plan"],["Focus study time on highest-weight domains","Take practice tests weekly from week 3","Schedule the exam to create deadline pressure"]),
("training","skill-gap-analysis","Team Skill Gap Analysis","Identify skill gaps in your team and plan development","Conduct a skill gap analysis for [TEAM]. Steps: (1) List required skills for the team's goals, (2) Rate current team capability (1-5) for each skill, (3) Identify gaps (required vs current), (4) Prioritise gaps by business impact, (5) Recommend development actions for each (training, hiring, mentoring). Present as a gap analysis matrix.",["chatgpt","claude"],"chatgpt",["manager","hr","team-lead"],"intermediate",["training","skill-gap","development","team"],["Involve team members in self-assessment","Focus on gaps that block strategic goals","Mix learning methods — not everything needs a course"]),
("training","lunch-and-learn","Lunch and Learn Session Plan","Plan an engaging lunch and learn session","Plan a [DURATION — 30 / 45]-minute lunch and learn on [TOPIC] for [AUDIENCE]. Include: (1) Catchy title and promotion blurb, (2) Learning objectives (2-3), (3) Agenda with timing, (4) Interactive element (demo, poll, Q&A), (5) Key takeaways (3 max), (6) Resources for further learning. Keep it informal and engaging — people are giving up their lunch break.",["chatgpt","claude"],"chatgpt",["trainer","manager","all"],"beginner",["training","lunch-learn","informal","session"],["Keep it practical — theory kills lunch and learns","Include one live demo or interactive exercise","Share slides and recording for those who cannot attend"]),

# SOCIAL-MEDIA +4
("social-media","thought-leadership-plan","Thought Leadership Content Plan","Build a personal thought leadership strategy","Build a thought leadership plan for [TOPIC/NICHE] on [PLATFORM]. Include: (1) Positioning statement (what I am known for), (2) Content pillars (3-4 themes), (3) Weekly posting cadence, (4) Content mix (original, curated, engagement), (5) Growth tactics, (6) 90-day content calendar with post ideas, (7) Metrics to track.",["chatgpt","claude"],"chatgpt",["all"],"intermediate",["social-media","thought-leadership","personal-brand"],["Consistency beats virality — post regularly","Share opinions not just facts","Engage with others in your niche daily"]),
("social-media","viral-hook","Viral Hook Generator","Generate scroll-stopping opening lines for social posts","Generate [NUMBER — 10 / 15] scroll-stopping opening hooks for posts about [TOPIC]. Types: (1) Contrarian opinion, (2) Surprising statistic, (3) Personal story starter, (4) Question that makes people think, (5) Bold prediction. Each hook should make someone stop scrolling in under 2 seconds.",["chatgpt","claude"],"chatgpt",["content-creator","marketing"],"beginner",["social-media","hooks","engagement","viral"],["The first line is the most important line","Test hooks by reading them to someone — do they want to hear more","Contrarian hooks get the most comments"]),
("social-media","community-engagement","Community Engagement Playbook","Create a strategy for building engaged communities","Create a community engagement playbook for [BRAND/COMMUNITY] on [PLATFORM]. Include: (1) Community guidelines, (2) Daily engagement routine (respond, initiate, amplify), (3) Content that sparks discussion, (4) How to handle negative comments, (5) Member recognition programme, (6) Growth targets and metrics, (7) Crisis response for community issues.",["chatgpt","claude"],"chatgpt",["marketing","community-manager"],"advanced",["social-media","community","engagement","strategy"],["Respond to every genuine comment — even just a like","Celebrate community members publicly","Address negative comments quickly and professionally"]),
("social-media","video-content-ideas","Short Video Content Ideas","Generate ideas for short-form video content","Generate [NUMBER — 10 / 15] short-form video ideas for [TOPIC/NICHE] on [PLATFORM — TikTok / Reels / Shorts]. For each: (1) Concept in one sentence, (2) Hook (first 3 seconds), (3) Format (tutorial / story / reaction / tips), (4) Length (15s / 30s / 60s), (5) Trending audio or style to leverage. Focus on ideas that showcase expertise without being boring.",["chatgpt","claude"],"chatgpt",["content-creator","marketing"],"beginner",["social-media","video","short-form","ideas"],["First 3 seconds determine if people watch","Show do not tell — demonstrate visually","Repurpose successful written content as videos"]),

# AUTOMATION +4
("automation","approval-workflow","Approval Workflow Designer","Design a multi-step approval workflow","Design an approval workflow for [PROCESS]. Include: (1) Form fields, (2) Routing rules (by amount, type, department), (3) Escalation if unapproved within [TIME], (4) Notifications (submitted, approved, rejected, escalated), (5) Audit trail. Power Automate actions specified.",["m365-copilot"],"m365-copilot",["it-admin","operations"],"intermediate",["automation","approval","power-automate"],["Keep chains short — each step adds delay","Auto-approve low-value items","Test with out-of-office approvers"]),
("automation","data-pipeline","Data Pipeline Designer","Design an automated data pipeline between systems","Design a data pipeline from [SOURCE] to [DESTINATION] for [PURPOSE]. Include: (1) Data extraction method, (2) Transformation rules, (3) Loading strategy (full vs incremental), (4) Schedule, (5) Error handling and alerting, (6) Data quality checks, (7) Monitoring dashboard. Consider volume, freshness, and reliability.",["chatgpt","claude"],"chatgpt",["data-engineer","analyst","it-admin"],"advanced",["automation","data-pipeline","etl","integration"],["Start with incremental loads for efficiency","Build data quality checks before loading","Monitor for silent failures"]),
("automation","notification-system","Smart Notification System","Design a notification system that reduces noise","Design a notification system for [TOOL/PROCESS] that reduces noise. Include: (1) Notification categories by urgency, (2) Channel routing rules (email for urgent, Teams for FYI, digest for low), (3) Frequency caps, (4) Quiet hours, (5) User preference settings, (6) Escalation for unacknowledged critical alerts.",["chatgpt","claude"],"chatgpt",["it-admin","operations","developer"],"intermediate",["automation","notifications","design","ux"],["Every notification should require or inform action","Batch low-priority notifications into digests","Let users control their preferences"]),
("automation","onboarding-automation","Employee Onboarding Automation","Automate the new hire onboarding process","Design an automated onboarding workflow triggered when HR adds a new hire. Steps: (1) Create accounts and assign licences, (2) Add to groups and distribution lists, (3) Send welcome email with setup instructions, (4) Create onboarding task list, (5) Schedule orientation meetings, (6) Assign buddy, (7) Day-30 check-in reminder to manager.",["m365-copilot"],"m365-copilot",["it-admin","hr","operations"],"advanced",["automation","onboarding","workflow","hr"],["Test with a fake account first","Include manual checkpoints for security tasks","Have a fallback for when automation fails"]),

# POWERPOINT +4
("powerpoint","problem-solution","Problem-Solution Deck","Create a problem-solution presentation structure","Create a [NUMBER]-slide problem-solution deck for [TOPIC]. Structure: (1) Hook with the problem statement, (2) Scale of the problem with data, (3) Why current approaches fail, (4) Our proposed solution, (5) How it works (3 steps max), (6) Evidence and proof points, (7) Investment required, (8) Expected outcomes, (9) Next steps and CTA.",["m365-copilot","chatgpt","claude"],"m365-copilot",["manager","sales","consultant"],"intermediate",["powerpoint","problem-solution","persuasion"],["The problem slides should make the audience feel the pain","Solution should feel like the obvious answer to the problem","End with one clear action"]),
("powerpoint","onboarding-deck","New Hire Onboarding Deck","Create a welcoming onboarding presentation for new employees","Create a [NUMBER]-slide onboarding deck for new hires joining [TEAM/COMPANY]. Include: (1) Welcome and company mission, (2) Team structure and who is who, (3) What we do and why it matters, (4) Tools and systems overview, (5) Key processes and how we work, (6) Culture and values, (7) First week expectations, (8) Resources and contacts, (9) Q&A. Tone: welcoming, not overwhelming.",["m365-copilot","chatgpt","claude"],"m365-copilot",["manager","hr"],"beginner",["powerpoint","onboarding","new-hire"],["Keep it visual — new hires are already overwhelmed with text","Include photos of team members","Share the deck before day 1 so they can review"]),
("powerpoint","monthly-update","Monthly Team Update Deck","Create a structured monthly team update presentation","Create a [NUMBER]-slide monthly update for [TEAM/DEPARTMENT]. Include: (1) Headline achievement this month, (2) Key metrics dashboard, (3) Wins and highlights, (4) Challenges and how we handled them, (5) Team shoutouts, (6) Next month priorities, (7) Resources or support needed. Each slide: one message, visual over text.",["m365-copilot"],"m365-copilot",["manager","team-lead"],"beginner",["powerpoint","monthly","update","team"],["Start with wins to set positive tone","Keep metrics to 4-6 — not a data dump","Shout-outs boost team morale significantly"]),
("powerpoint","sales-enablement","Sales Enablement Deck","Create a deck that helps sales teams sell effectively","Create a sales enablement deck for [PRODUCT/SERVICE]. Include: (1) Elevator pitch (30 seconds), (2) Target customer profile, (3) Key pain points we solve (with customer quotes), (4) Product overview (features mapped to benefits), (5) Competitive positioning (us vs alternatives), (6) Pricing and packaging, (7) Objection handling, (8) Case studies, (9) Next step CTA.",["m365-copilot","chatgpt","claude"],"m365-copilot",["sales","marketing","product-manager"],"intermediate",["powerpoint","sales","enablement","deck"],["Sales reps will only use 5-10 slides — make every one count","Include competitor battle cards as appendix","Test with actual sales reps before distributing"]),

# PLANNING +4
("planning","business-case","Business Case Template","Build a structured business case for approval","Write a business case for [INITIATIVE]. Include: (1) Executive summary, (2) Problem with data, (3) Proposed solution, (4) Options (including do nothing), (5) Costs, (6) Benefits, (7) Timeline, (8) Risks, (9) Recommendation. Format for [AUDIENCE].",["m365-copilot","chatgpt","claude"],"claude",["manager","executive"],"advanced",["planning","business-case","investment"],["Lead with financial impact","Include cost of inaction","Keep under 3 pages"]),
("planning","strategic-review","Strategic Review Framework","Conduct a structured strategic review of performance","Create a strategic review framework for [BUSINESS AREA] covering [PERIOD]. Include: (1) Mission and strategy recap, (2) Performance vs goals, (3) What worked and why, (4) What did not work and root causes, (5) Market and competitive changes, (6) Resource utilisation, (7) Priorities for next period, (8) Key bets and experiments to run.",["chatgpt","claude"],"claude",["executive","strategy","manager"],"advanced",["planning","strategic","review","performance"],["Be honest about what did not work","Include external factors that affected performance","End with clear priorities not just observations"]),
("planning","team-offsite","Team Offsite Agenda","Plan a productive and engaging team offsite","Plan a [DURATION]-day team offsite for [TEAM]. Include: (1) Objectives (what we want to walk away with), (2) Agenda with session timing, (3) Strategic sessions (vision, priorities, OKRs), (4) Team building activities, (5) Working sessions with clear outputs, (6) Social programme, (7) Pre-work for participants, (8) Follow-up actions framework.",["chatgpt","claude"],"chatgpt",["manager","executive","hr"],"intermediate",["planning","offsite","team","agenda"],["Balance strategy with team building","Include working time with clear outputs","Send pre-read so sessions are productive"]),
("planning","decision-framework","Decision Framework Builder","Create a structured framework for making a specific decision","Build a decision framework for [DECISION]. Include: (1) Decision statement, (2) Decision criteria with weights, (3) Options to evaluate, (4) Scoring template, (5) Risk assessment per option, (6) Stakeholder input needed, (7) Timeline and decision deadline, (8) Communication plan for the decision. Help us make this decision objectively.",["chatgpt","claude"],"claude",["manager","executive","project-manager"],"advanced",["planning","decision","framework","analysis"],["Define criteria before evaluating options to avoid bias","Include do nothing as an option","Document the framework for future similar decisions"]),

# LEGAL +4
("legal","nda-summary","NDA Quick Summary","Summarise an NDA highlighting key obligations","Summarise this NDA: (1) What is confidential, (2) What is excluded, (3) Duration of obligations, (4) Permitted disclosures, (5) Return of information requirements, (6) Which party has more restrictions, (7) Governing law. Flag anything unusual. Note: consult legal for binding advice.",["m365-copilot","chatgpt","claude"],"claude",["legal","manager","sales"],"intermediate",["legal","nda","confidentiality"],["Check if mutual or one-way","Watch the definition of confidential information","Note the survival period"]),
("legal","terms-review","Terms of Service Review","Summarise terms of service for a tool your team wants to use","Summarise the ToS for [TOOL/SERVICE] focusing on: (1) Data ownership, (2) How they use our data, (3) Liability limits, (4) Termination and data portability, (5) Acceptable use, (6) SLA commitments, (7) Price change provisions, (8) Red flags for enterprise use. Keep under one page.",["chatgpt","claude","perplexity"],"claude",["legal","it-admin","procurement"],"intermediate",["legal","terms","service","review"],["Always review ToS before adding tools","Check AI training clauses","Watch for unilateral change provisions"]),
("legal","data-processing-review","Data Processing Agreement Review","Review a DPA and flag key obligations","Review this DPA: (1) Data processed, (2) Purposes, (3) Controller vs processor duties, (4) Sub-processors, (5) Cross-border transfers, (6) Breach notification timeframes, (7) Audit rights, (8) Data return on termination. Flag deviations from standard clauses.",["chatgpt","claude"],"claude",["legal","compliance"],"advanced",["legal","dpa","data-processing"],["Compare against your standard DPA","Check sub-processor provisions carefully","Ensure breach notification is realistic"]),
("legal","ip-assignment","IP Assignment Checklist","Review intellectual property assignment provisions","Review this agreement for IP provisions: (1) Who owns work product, (2) Background IP treatment, (3) Licence grants, (4) Assignment of rights, (5) Third-party IP usage, (6) Open source obligations, (7) Moral rights waiver, (8) IP warranties. Flag any provisions that limit our ownership of deliverables.",["chatgpt","claude"],"claude",["legal","manager","procurement"],"advanced",["legal","ip","intellectual-property","assignment"],["IP ownership should be clear in every contract","Watch for licence-back provisions that limit your use","Check if contractors own anything they create"]),

# TROUBLESHOOTING +3
("troubleshooting","network-diagnosis","Network Connectivity Diagnosis","Systematically troubleshoot network connectivity issues","Help me diagnose this network issue: [SYMPTOMS]. Walk through: (1) Client-side checks (IP, DNS, gateway), (2) Internal network checks (switches, VLAN, firewall rules), (3) External connectivity (ISP, DNS resolution, latency), (4) Application-specific checks, (5) Recent changes that might correlate. Provide commands to run at each step.",["m365-copilot","chatgpt"],"chatgpt",["it-admin","support"],"intermediate",["troubleshooting","network","connectivity","diagnosis"],["Start with the simplest test — can they ping the gateway","Check if the issue affects one user or many — this changes the diagnosis","Document every test result for the escalation"]),
("troubleshooting","login-failure","Login and Authentication Troubleshooting","Diagnose common login and authentication failures","Create a troubleshooting guide for login failures in [SYSTEM — M365 / VPN / application]. Cover: (1) Password issues (expired, locked, forgotten), (2) MFA problems (lost device, token expired), (3) Conditional Access blocks, (4) Account disabled, (5) SSO failures, (6) Browser and cache issues. For each: symptoms, diagnosis steps, resolution, and prevention.",["m365-copilot","chatgpt"],"chatgpt",["it-admin","support"],"beginner",["troubleshooting","login","authentication","mfa"],["Login issues are the second most common support ticket","Always check Entra ID sign-in logs first","Include self-service password reset instructions"]),
("troubleshooting","email-delivery","Email Delivery Troubleshooting","Diagnose why emails are not being delivered","Help me diagnose email delivery failure. Scenario: [DESCRIBE — emails not received / going to spam / bouncing / delayed]. Check: (1) Message trace in Exchange Admin, (2) SPF/DKIM/DMARC alignment, (3) Transport rules that might redirect, (4) Recipient mailbox issues, (5) IP reputation, (6) Content filtering triggers. Provide step-by-step diagnosis with Exchange admin paths.",["m365-copilot","chatgpt"],"chatgpt",["it-admin","support"],"intermediate",["troubleshooting","email","delivery","exchange"],["Message trace is your best friend for email issues","Check transport rules — they silently redirect more than you expect","SPF/DKIM failures cause legitimate emails to land in spam"]),

# PRODUCTIVITY +3
("productivity","morning-routine","Morning Productivity Routine","Design an optimal morning routine for maximum productivity","Design a morning routine for a [ROLE] who starts work at [TIME]. Include: (1) Pre-work ritual (15 min), (2) Planning block (10 min — review calendar, set daily top 3), (3) Deep work block (60-90 min on most important task), (4) Communication check (15 min — email and Teams triage), (5) First meeting prep. Base on research about peak productivity times.",["chatgpt","claude"],"chatgpt",["all"],"beginner",["productivity","morning","routine","habits"],["Do your most important work before checking email","Your first 90 minutes are your most productive — protect them","Batch communications instead of checking continuously"]),
("productivity","delegation-framework","Delegation Decision Framework","Decide what to delegate and create clear handoffs","Help me decide what to delegate from: [LIST TASKS]. For each evaluate: (1) Must I personally do this?, (2) Who could do this?, (3) What support would they need?, (4) What does a good handoff look like? Create delegation briefs for the top [NUMBER] tasks to hand off.",["m365-copilot","chatgpt","claude"],"chatgpt",["manager","executive"],"intermediate",["productivity","delegation","management"],["Delegate the task not the decision","Set check-in points not micromanagement","If you cannot delegate 30 percent your team is under-utilised"]),
("productivity","meeting-audit","Meeting Audit and Cleanup","Analyse your meeting load and reclaim time","Audit my calendar for [WEEKS] weeks. Categorise each recurring meeting as: (1) Essential, (2) Optional — could send delegate, (3) Redundant — overlaps another, (4) Unnecessary — should be an email. Draft opt-out messages for non-essential. Calculate hours I could reclaim per week.",["m365-copilot"],"m365-copilot",["manager","executive"],"intermediate",["productivity","meetings","audit","time"],["Most professionals spend 50 percent in meetings — reclaim some","Challenge if every meeting needs to be an hour","Suggest async alternatives for status updates"]),

# COMMUNICATION +3
("communication","change-notice","Change Management Communication","Write a change notice for employees","Draft a change communication for [CHANGE]. Include: (1) What is changing and why, (2) What stays the same, (3) Timeline, (4) Training and support, (5) FAQ, (6) Feedback channel. Tone: supportive, clear, proactive.",["m365-copilot","chatgpt","claude"],"m365-copilot",["communications","hr","it-admin"],"intermediate",["communication","change","notice"],["Send well before the change","Address what is in it for me upfront","Multiple support channels"]),
("communication","newsletter","Internal Newsletter Builder","Create a readable internal newsletter","Create a newsletter for [AUDIENCE]. Include: (1) Subject line, (2) Short intro, (3) 3-4 scannable sections, (4) Employee spotlight, (5) Upcoming dates, (6) CTA. Reading time under 3 minutes.",["m365-copilot","chatgpt","claude"],"chatgpt",["communications","hr"],"beginner",["communication","newsletter","internal"],["Keep sections to 2-3 sentences plus a link","Include a human interest story","Send at consistent times"]),
("communication","executive-briefing","Executive Briefing Note","Write a concise briefing note for leadership","Write a one-page briefing on [TOPIC] for [AUDIENCE]. Structure: (1) Bottom line (one sentence), (2) Context, (3) Key facts (3-5 bullets), (4) Options with pros and cons, (5) Recommendation, (6) Talking points for cascading.",["m365-copilot","chatgpt","claude"],"claude",["executive-assistant","manager"],"advanced",["communication","executive","briefing"],["Put recommendation first","Keep to one page","Include talking points"]),

# FINANCE +3
("finance","budget-template","Budget Planning Template","Create a departmental budget template","Create a budget template for [DEPARTMENT] for [YEAR]. Include: revenue categories, operating expenses (personnel, software, travel), capital expenses, monthly breakdowns, variance tracking (budget vs actual), summary row with ratios.",["m365-copilot","chatgpt"],"m365-copilot",["finance","manager"],"intermediate",["finance","budget","planning"],["Base on actual spend plus known changes","Include 5-10 percent contingency","Review monthly not quarterly"]),
("finance","expense-variance","Expense Variance Analysis","Analyse budget vs actual spending","Analyse expense variance for [PERIOD]. For items varying by more than [THRESHOLD]: (1) Variance amount and percentage, (2) Favourable or unfavourable, (3) Likely cause, (4) One-time vs trend, (5) Corrective action. Summarise total impact.",["m365-copilot"],"m365-copilot",["finance","analyst"],"intermediate",["finance","variance","analysis"],["Focus on material variances only","Distinguish timing from true overspends","One-line recommendation per material variance"]),
("finance","financial-summary","Monthly Financial Summary","Create an executive-ready financial summary","Create a monthly financial summary for [PERIOD]. Include: revenue vs target, key expenses, profitability, cash flow, top 3 risks, next month outlook. One-page executive format with traffic lights.",["m365-copilot","chatgpt"],"m365-copilot",["finance","executive"],"advanced",["finance","reporting","summary"],["Lead with the headline number","Use RAG for instant scanning","Include context for alarming numbers"]),

# MARKETING +3
("marketing","persona-builder","Customer Persona Builder","Create detailed customer personas","Build [NUMBER] customer personas for [PRODUCT]. For each: name, role, demographics, goals, pain points, discovery channels, objections, preferred channels, a quote capturing their mindset. Base on [DATA SOURCE].",["m365-copilot","chatgpt","claude"],"chatgpt",["marketing","product-manager"],"intermediate",["marketing","persona","audience"],["Ground in real customer data","Update annually","Share with sales and product"]),
("marketing","seo-content-brief","SEO Content Brief","Create a content brief targeting specific keywords","Create an SEO brief for [PRIMARY KEYWORD]. Include: target keyword and related terms, search intent, competitor review (top 3), word count, heading structure, key points, internal linking, featured snippet opportunity.",["chatgpt","perplexity"],"perplexity",["marketing","seo"],"advanced",["marketing","seo","content-brief"],["Match search intent exactly","Include related People Also Ask questions","Brief should be executable by any writer"]),
("marketing","product-launch","Product Launch Plan","Create a multi-channel product launch plan","Create a launch plan for [PRODUCT]. Include: messaging framework, press release draft, blog outline, 5 social posts, internal announcement, customer email. All using consistent messaging.",["m365-copilot","chatgpt","claude"],"claude",["marketing","product-manager"],"advanced",["marketing","launch","product"],["Align all channels same day and message","Brief sales before external announcement","Include FAQ for customer-facing teams"]),
]

for args in P:
    wp(*args)

total = sum(1 for p in Path(BASE).rglob("*.md") if p.name != "_index.md")
print(f"Created {count} prompts")
print(f"GRAND TOTAL: {total}")
